### ISSUE TITLE
Add authentication and Authorization to the app

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/self-evaluator#21]
we need to add **sign in**, **sign up** and **logout** functionality. also we should consider limiting login attempts for login and sign up per IP, this will make our application more secure in case of any Bruteforce attack.

**To-Do:**

- [x] add login functionality
- [x] add sign up functionality
- [x] add logout functionality
- [x] limit number of attempts to login per IP
