### ISSUE TITLE
Add appropriate message alerts

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/self-evaluator#26]
Display different types of alerts including: **error** **warning** and **info** messages in an appropriate format using **Flush**.

### To-Do:
- [x] add flush method and using appropriate messages in case of needs
- [x] create alert class in css
- [x] create alert-error class in css
- [x] create alert-warning class in css
- [x] create alert-info class in css

**Comment by abdolmajidbn** [comment]
I'm ready to participate and solve this issue :smile:

**Comment by abdolmajidbn** [comment]
Everything is fine
