### ISSUE TITLE
Use jinja templating for back-end

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/self-evaluator#29]
we should separate header and footer files and then include in main templates, using jinja which is the Flask templating engine.
### To-Do:

- [ ] create templates directory
- [ ] create header file
- [ ] create footer file
- [ ] create main template and include header and footer
- [ ] extend main template in all static pages
